security:
  basic:
    enabled: true
  user:
    name: user
    password: liuly
server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lyliu/spring-config-cloud-learning
          username:
          password:
  application:
    name: microserver-cloud-config-server-auth
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
