server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lyliu/spring-config-cloud-learning
          username:
          password:
  application:
    name: microserver-cloud-config-server

# 对称加密的秘钥因子
#encrypt:
#  key: key123

#rsa 加密的姿势
# curl -X POST http://localhost:8080/encrypt -d liuly
# curl -X POST http://localhost:8080/decrypt -d  '生成一长串密文'
# keytool -genkeypair -alias mytestkey -keyalg RSA -dname "CN=Web Server,OU=Unit,O=Organization,L=City,S=State,C=US" -keypass changeme -keystore server.jks -storepass letmine
encrypt:
  keyStore:
    location: classpath:/server.jks   # server.jks的配置文件的路径
    password: letmine      # 设置store的密码
    alias: mytestkey
    secret: changeme