server:
  port: 9000
spring:
  application:
    name: microserver-provider-movie-feign
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    appname: microserver-provider-movie-feign
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

 